# Site settings
title: Jaron Heard
email: jaronheard@gmail.com
url: https://jaronheard.github.io
description: "Jaron Heard"
skills: "DATA VISUALIZATION"
safe: true
lsi: false

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 007C8A #80B3FF
  primary-rgb: "0,124,138" #"128,179,255"
  secondary: A5B09E #FD6E8A
  secondary-dark: 183F4B #A2122F

# Footer settings
footer:
  copyright: Jaron Heard
  location: Portland
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jaronheard
  - title: facebook
    url: http://facebook.com/jaronheard
  - title: github
    url: http://github.com/jaronheard
  - title: linkedin
    url: https://www.linkedin.com/in/jaron-heard-63251179

# Postal address (add as many lines as necessary)
address:
  - line: 3227 SE Stark St.
  - line: Portland, OR, 97214

# Credits content
credits: 'Based on a modified version of the Freelancer Bootstrap theme.'

# Build settings
markdown: kramdown
permalink: pretty
